-- LIBRARY OF WEAPONS AND CLASSES
firearms = {
    ["Pistol"] = {
        "WEAPON_REVOLVER", "WEAPON_PISTOL", "WEAPON_PISTOL_MK2", "WEAPON_COMBATPISTOL", "WEAPON_APPISTOL", "WEAPON_PISTOL50", "WEAPON_SNSPISTOL", 
        "WEAPON_HEAVYPISTOL", "WEAPON_VINTAGEPISTOL", "WEAPON_DOUBLEACTION", "WEAPON_REVOLVER_MK2", "WEAPON_SNSPISTOL_MK2", "WEAPON_CERAMICPISTOL",
        "WEAPON_GLOCK", "WEAPON_SIGP226"
    },
    ["SMG"] = {
        "WEAPON_MICROSMG", "WEAPON_MINISMG", "WEAPON_SMG", "WEAPON_SMG_MK2", "WEAPON_ASSAULTSMG", "WEAPON_MACHINEPISTOL",
    },
    ["Assault"] = {
        "WEAPON_ASSAULTRIFLE", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_CARBINERIFLE", "WEAPON_CARBINERIFLE_MK2", "WEAPON_ADVANCEDRIFLE", "WEAPON_SPECIALCARBINE", 
        "WEAPON_BULLPUPRIFLE", "WEAPON_COMPACTRIFLE", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_MILITARYRIFLE"
    },
    ["Shotgun"] = {
        "WEAPON_PUMPSHOTGUN", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_BULLPUPSHOTGUN", "WEAPON_ASSAULTSHOTGUN", "WEAPON_HEAVYSHOTGUN", "WEAPON_DBSHOTGUN",
        "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_COMBATSHOTGUN",
    },
    ["Snipers"] = {
        "WEAPON_HEAVYSNIPER", "WEAPON_SNIPERRIFLE", "WEAPON_MARKSMANRIFLE"
    }
}
