-- LIST OF BED PROP HASHES THAT PLAYERS CAN LIE ON
beds = {"v_med_bed1", "v_med_bed2", "v_med_emptybed", "gabz_pillbox_diagnostics_bed_01", "gabz_pillbox_diagnostics_bed_02",
"gabz_pillbox_diagnostics_bed_03"}

-- KNIVES TO MAKE PLAYER BLEED MORE FREQUENTLY IF STABBED
knives = {"WEAPON_KNIFE", "WEAPON_BOTTLE", "WEAPON_DAGGER", "WEAPON_HATCHET", "WEAPON_MACHETE", "WEAPON_SWITCHBLADE", "WEAPON_BATTLEAXE"}

-- WEAPON GROUPS TO BE DEFINED BY PLAYER TRIAGE
weaponGroups = {
    [-728555052] = "Blunt",
    [860033945] = "Buck shot",
    [1548507267] = "Projectile",
    [416676503] = "Low caliber gunshot",
    [-957766203] = "Low caliber gunshot",
    [970310034] = "High caliber gunshot",
    [-1212426201] = "High caliber gunshot",
    [-1569042529] = "Heavy caliber gunshot"
}

-- GENERATED WHEN A LOCAL IS TRIAGED, GENERATES WHAT THEIR INJURIES COULD BE
causesOfDeath = {
    ["WEAPON_KNIFE"] = "stab wounds",
    ["WEAPON_DAGGER"] = "a small stab wound",
    ["WEAPON_HATCHET"] = "a large stab wound",
    ["WEAPON_BOTTLE"] = "a couple stab wounds",
    ["WEAPON_NIGHTSTICK"] = "blunt force trauma",
    ["WEAPON_UNARMED"] = "bruises and a black eye",
    ["WEAPON_SMG"] = "small caliber gunshot wounds",
    ["WEAPON_MINISMG"] = "small caliber gunshot wounds",
    ["WEAPON_COUGAR"] = "mountain lion bites and scratches",
    ["WEAPON_HAMMER"] = "blunt force trauma",
    ["WEAPON_BAT"] = "blunt force trauma",
    ["WEAPON_GOLFCLUB"] = "blunt force trauma",
    ["WEAPON_CROWBAR"] = "blunt force trauma",
    ["WEAPON_PISTOL"] = "small caliber gunshot wounds",
    ["WEAPON_COMBATPISTOL"] = "small caliber gunshot wounds",
    ["WEAPON_APPISTOL"] = "small caliber gunshot wounds",
    ["WEAPON_MACHINEPISTOL"] = "small caliber gunshot wounds",
    ["WEAPON_SNSPISTOL"] = "small caliber gunshot wounds",
    ["WEAPON_SNSPISTOL_MK2"] = "small caliber gunshot wounds",
    ["WEAPON_MICROSMG"] = "small caliber gunshot wounds",
    ["WEAPON_ASSAULTRIFLE"] = "high caliber gunshot wounds",
    ["WEAPON_CARBINERIFLE"] = "high caliber gunshot wounds",
    ["WEAPON_STUNGUN"] = "multiple taser prong wounds",
    ["WEAPON_VINTAGEPISTOL"] = "small caliber gunshot wounds",
    ["WEAPON_BATTLEAXE"] = "a large stab wound",
    ["WEAPON_KNUCKLE"] = "bruises and what appears to be marks left from a knuckle duster",
}

bones = {
    [0] = "mid-section",
    [839] = "tail",
    [840] = "tail",
    [841] = "tail",
    [842] = "tail",
    [1356] = "eyebrows",
    [2108] = "left foot toes",
    [2992] = "elbow",
    [4089] = "left ring finger",
    [4090] = "left pinky",
    [4137] = "left index finger",
    [4138] = "left middle finger",
    [4153] = "left thumb",
    [4154] = "left ring finger",
    [4169] = "left pinky",
    [4170] = "left index finger",
    [4185] = "left middle finger",
    [4186] = "left thumb",
    [5232] = "left arm",
    [6286] = "right hand",
    [6442] = "right thigh",
    [10706] = "right clavicle",
    [11174] = "lips",
    [11816] = "pelvis",
    [12844] = "head",
    [14201] = "left foot",
    [16335] = "right knee",
    [17188] = "lips",
    [17719] = "lips",
    [18905] = "left hand",
    [19336] = "right cheek",
    [20178] = "lips",
    [20279] = "lips",
    [20623] = "lips",
    [20781] = "right foot toes",
    [21550] = "left cheek",
    [22711] = "elbow",
    [23553] = "mid-section",
    [23639] = "left thigh",
    [24806] = "right foot",
    [24816] = "abdomen",
    [24817] = "lower chest",
    [24818] = "upper chest",
    [25260] = "left eye",
    [26610] = "left pinky",
    [26611] = "left ring finger",
    [26612] = "left middle finger",
    [26613] = "left index finger",
    [26614] = "left thumb",
    [27474] = "right eye",
    [28252] = "right forearm",
    [28422] = "right hand",
    [29868] = "lips",
    [31086] = "head",
    [35502] = "right foot",
    [35731] = "neck",
    [36029] = "left hand",
    [36864] = "right calf",
    [37119] = "right arm",
    [37193] = "eyebrows",
    [39317] = "neck",
    [40269] = "upper arm",
    [43536] = "lips",
    [43810] = "forearm",
    [45509] = "upper arm",
    [45750] = "lips",
    [46078] = "left knee",
    [46240] = "jaw",
    [47419] = "lips",
    [47495] = "tongue",
    [49979] = "lips",
    [51826] = "right thigh",
    [52301] = "right foot",
    [56604] = "mid-region",
    [57005] = "right hand",
    [57597] = "mid-region",
    [57717] = "left foot",
    [58271] = "left thigh",
    [58331] = "eyebrows",
    [58866] = "right pinky",
    [58867] = "right ring finger",
    [58868] = "right middle finger",
    [58869] = "right index finger",
    [58870] = "right thumb",
    [60309] = "left hand",
    [61007] = "left forearm",
    [61163] = "left forearm",
    [61839] = "lips",
    [63931] = "left calf",
    [64016] = "right pinky",
    [64017] = "right ring finger",
    [64064] = "right middle finger",
    [64065] = "right index finger",
    [64080] = "right thumb",
    [64081] = "right pinky",
    [64096] = "right ring finger",
    [64097] = "right middle finger",
    [64112] = "right index finger",
    [64113] = "right thumb",
    [64729] = "left clavicle",
    [65068] = "face",
    [65245] = "foot"
}

weapons = {
    "WEAPON_UNARMED",
    "WEAPON_KNIFE",
    "WEAPON_KNUCKLE",
    "WEAPON_NIGHTSTICK",
    "WEAPON_HAMMER",
    "WEAPON_BAT",
    "WEAPON_GOLFCLUB",
    "WEAPON_CROWBAR",
    "WEAPON_BOTTLE",
    "WEAPON_DAGGER",
    "WEAPON_HATCHET",
    "WEAPON_MACHETE",
    "WEAPON_FLASHLIGHT",
    "WEAPON_SWITCHBLADE",
    "WEAPON_SMOKEGRENADE",
    "WEAPON_MOLOTOV",
    "WEAPON_FIREEXTINGUISHER",
    "WEAPON_PETROLCAN",
    "WEAPON_SNOWBALL",
    "WEAPON_FLARE",
    "WEAPON_REVOLVER",
    "WEAPON_POOLCUE",
    "WEAPON_PIPEWRENCH",
    "WEAPON_PISTOL",
    "WEAPON_PISTOL_MK2",
    "WEAPON_COMBATPISTOL",
    "WEAPON_APPISTOL",
    "WEAPON_PISTOL50",
    "WEAPON_SNSPISTOL",
    "WEAPON_HEAVYPISTOL",
    "WEAPON_VINTAGEPISTOL",
    "WEAPON_STUNGUN",
    "WEAPON_FLAREGUN",
    "WEAPON_MARKSMANPISTOL",
    "WEAPON_MICROSMG",
    "WEAPON_MINISMG",
    "WEAPON_SMG",
    "WEAPON_ASSAULTSMG",
    "WEAPON_GUSENBERG",
    "WEAPON_MACHINEPISTOL",
    "WEAPON_ASSAULTRIFLE",
    "WEAPON_CARBINERIFLE",
    "WEAPON_CARBINERIFLE_MK2",
    "WEAPON_ADVANCEDRIFLE",
    "WEAPON_SPECIALCARBINE",
    "WEAPON_BULLPUPRIFLE",
    "WEAPON_COMPACTRIFLE",
    "WEAPON_PUMPSHOTGUN",
    "WEAPON_SWEEPERSHOTGUN",
    "WEAPON_SAWNOFFSHOTGUN",
    "WEAPON_MUSKET",
    "WEAPON_HEAVYSHOTGUN",
    "WEAPON_DBSHOTGUN",
    "WEAPON_SNIPERRIFLE",
    "WEAPON_HEAVYSNIPER",
    "WEAPON_HEAVYSNIPER_MK2",
    "WEAPON_MARKSMANRIFLE",
    "WEAPON_FIREWORK",
    "WEAPON_SNSPISTOL_MK2",
    "WEAPON_REVOLVER_MK2",
    "WEAPON_DOUBLEACTION",
    "WEAPON_PUMPSHOTGUN_MK2",
    "WEAPON_MARKSMANRIFLE_MK2",
    "WEAPON_HIT_BY_WATER_CANNON",
    "WEAPON_RUN_OVER_BY_CAR",
    "WEAPON_COUGAR"
}
