furnitureProps = {
    -- BATHROOM
    ["prop_ld_toilet_01"] = {type = "bathroom", itemHash = "dirtytoilet", name = "Dirty Toilet"},
    ["prop_toilet_01"] = {type = "bathroom", itemHash = "toilet", name = "Toilet"},
    ["prop_toilet_02"] = {type = "bathroom", itemHash = "toilet2", name = "Small Toilet"},
    ["prop_toilet_brush_01"] = {type = "bathroom", itemHash = "toiletbrush", name = "Toilet Brush"},
    ["prop_cleaning_trolly"] = {type = "bathroom", itemHash = "cleaningtrolly", name = "Cleaning Trolly"},
    ["apa_mp_h_bathtub_01"] = {type = "bathroom", itemHash = "bathtub", name = "Bathtub"},
    ["p_new_j_counter_02"] = {type = "bathroom", itemHash = "bathroomcounter", name = "Bathroom Counter"},
    ["prop_sink_05"] = {type = "bathroom", itemHash = "bathroomsink", name = "Bathroom Bowl Sink"},
    ["prop_sink_06"] = {type = "bathroom", itemHash = "bathroomsink2", name = "Bathroom Sink"},
    ["prop_toilet_roll_02"] = {type = "bathroom", itemHash = "toiletrollholder", name = "Toilet Roll Holder"},
    ["prop_medstation_01"] = {type = "bathroom", itemHash = "medstation", name = "First Aid Cabinet"},
    ["prop_medstation_03"] = {type = "bathroom", itemHash = "medstation2", name = "First Aid Cabinet 2"},
    ["prop_medstation_04"] = {type = "bathroom", itemHash = "medstation3", name = "First Aid Cleaner"},
    ["p_pharm_unit_01"] = {type = "bathroom", itemHash = "medcabinet", name = "Medicine Cabinet 1"},
    ["p_pharm_unit_02"] = {type = "bathroom", itemHash = "medcabinet2", name = "Medicine Cabinet 2"},
    ["v_res_mlaundry"] = {type = "bathroom", itemHash = "lightfan", name = "Towel Basket"},
    ["v_res_fh_towelstack"] = {type = "bathroom", itemHash = "foldedtowels", name = "Folded Towels"},
    ["p_shower_towel_s"] = {type = "bathroom", itemHash = "largetowel", name = "Large Towel"},

    -- KITCHEN
    ["hei_heist_kit_bin_01"] = {type = "kitchen", itemHash = "bluebin", name = "Blue Bin"},
    ["prop_bin_10b"] = {type = "kitchen", itemHash = "orangebin", name = "Orange Bin"},
    ["prop_bar_fridge_03"] = {type = "kitchen", itemHash = "fridge", name = "Small Drinks Fridge"},
    ["prop_bar_fridge_04"] = {type = "kitchen", itemHash = "fridge2", name = "Double Drinks Fridge"},
    ["prop_bar_fridge_01"] = {type = "kitchen", itemHash = "fridge3", name = "Large Drinks Fridge"},
    ["prop_chip_fryer"] = {type = "kitchen", itemHash = "fryer", name = "Industrial Fryer"},
    ["prop_cooker_03"] = {type = "kitchen", itemHash = "cooker", name = "Industrial Cooker"},
    ["prop_bar_ice_01"] = {type = "kitchen", itemHash = "icecooler", name = "Industrial Ice Cooler"},
    ["prop_ff_sink_02"] = {type = "kitchen", itemHash = "industrialsink", name = "Industrial Sink"},
    ["prop_sink_02"] = {type = "kitchen", itemHash = "smallindustrialsink", name = "Kitchen Sink"},
    ["prop_fridge_01"] = {type = "kitchen", itemHash = "fridge4", name = "Industrial Fridge"},
    ["prop_fridge_03"] = {type = "kitchen", itemHash = "fridge5", name = "White Fridge"},
    ["prop_washer_02"] = {type = "kitchen", itemHash = "washer", name = "Washer"},
    ["prop_washer_03"] = {type = "kitchen", itemHash = "washer2", name = "Used Washer"},
    ["dlc_gtao_heist_planning_board_heist_board_print"] = {type = "kitchen", itemHash = "dryer", name = "Industrial Dryer"},
    ["p_kitch_juicer_s"] = {type = "kitchen", itemHash = "juicer", name = "Juicer"},
    ["prop_cs_kettle_01"] = {type = "kitchen", itemHash = "kettle", name = "White Kettle"},
    ["prop_kettle"] = {type = "kitchen", itemHash = "kettle2", name = "Grey Kettle"},
    ["prop_coffee_mac_02"] = {type = "kitchen", itemHash = "coffeemachine", name = "Coffee Machine"},
    ["prop_coffee_mac_01"] = {type = "kitchen", itemHash = "coffeemachine2", name = "Industrial Coffee Machine"},
    ["prop_juice_dispenser"] = {type = "kitchen", itemHash = "juicedispenser", name = "Juice Dispenser"},
    ["prop_slush_dispenser"] = {type = "kitchen", itemHash = "slushdispenser", name = "Slush Dispenser"},
    ["prop_food_bs_soda_01"] = {type = "kitchen", itemHash = "sodadispenser", name = "Soda Dispenser 1"},
    ["prop_food_cb_soda_01"] = {type = "kitchen", itemHash = "sodadispenser2", name = "Soda Dispenser 2"},
    ["prop_gumball_01"] = {type = "kitchen", itemHash = "gumballmachine", name = "Candy Machine"},
    ["prop_watercooler"] = {type = "kitchen", itemHash = "watercooler", name = "Water Cooler"},
    ["v_ret_ml_liqshelfc"] = {type = "kitchen", itemHash = "liquorshelf", name = "Liquor Collection Shelf"},
    ["prop_micro_02"] = {type = "kitchen", itemHash = "microwave", name = "White Microwave"},
    ["prop_microwave_1"] = {type = "kitchen", itemHash = "microwave2", name = "Grey Microwave"},
    ["prop_micro_04"] = {type = "kitchen", itemHash = "microwave3", name = "Vintage Microwave"},
    ["prop_toaster_02"] = {type = "kitchen", itemHash = "toaster", name = "White Toaster"},
    ["prop_toaster_01"] = {type = "kitchen", itemHash = "toaster2", name = "Cream Toaster"},
    ["v_res_tre_mixer"] = {type = "kitchen", itemHash = "kitchenmixer", name = "Kitchen Mixer"},
    ["v_res_mchopboard"] = {type = "kitchen", itemHash = "choppingboard", name = "Chopping Board"},
    ["prop_pot_rack"] = {type = "kitchen", itemHash = "potrack", name = "Pot Rack"},
    ["v_res_m_woodbowl"] = {type = "kitchen", itemHash = "fruitbowl", name = "Wooden Fruit Bowl"},
    ["apa_mp_h_acc_fruitbowl_02"] = {type = "kitchen", itemHash = "fruitbowl2", name = "White Fruit Bowl"},
    ["v_res_mkniferack"] = {type = "kitchen", itemHash = "kniferack", name = "Knife Rack"},
    ["prop_champset"] = {type = "kitchen", itemHash = "champagneset", name = "Champagne Set"},
    ["v_res_mplatelrg"] = {type = "kitchen", itemHash = "whiteplate", name = "White Plate"},
    ["v_res_cakedome"] = {type = "kitchen", itemHash = "cakedisplay", name = "Cake Display"},
    ["prop_bar_caddy"] = {type = "kitchen", itemHash = "barcaddy", name = "Bar Caddy"},
    ["beerrow_local"] = {type = "kitchen", itemHash = "beercollection", name = "Local Beer Collection"},
    ["beerrow_world"] = {type = "kitchen", itemHash = "beercollection2", name = "World Beer Collection"},
    ["v_res_foodjarb"] = {type = "kitchen", itemHash = "ricejar", name = "Rice Jar"},
    ["prop_pot_05"] = {type = "kitchen", itemHash = "kitchenpan", name = "Kitchen Pan"},
    ["v_res_r_teapot"] = {type = "kitchen", itemHash = "teapot", name = "Teapot"},
    ["prop_bikerset"] = {type = "kitchen", itemHash = "variousalcohols", name = "Various Alcohols"},
    ["v_res_foodjara"] = {type = "kitchen", itemHash = "pepperjar", name = "Dried Pepper Jar"},
    ["p_whiskey_bottle_s"] = {type = "kitchen", itemHash = "whiskeybottle", name = "Whiskey Bottle"},
    ["v_res_foodjarc"] = {type = "kitchen", itemHash = "pastajar", name = "Pasta Jar"},
    ["v_res_mbowl"] = {type = "kitchen", itemHash = "whitebowl", name = "White Bowl"},
    ["v_res_mmug"] = {type = "kitchen", itemHash = "whitemug", name = "White Mug"},
    ["v_res_mcofcup"] = {type = "kitchen", itemHash = "whitecup", name = "White Cup"},

    -- STORAGE
    ["prop_tv_cabinet_03"] = {type = "storage", itemHash = "tvcabinet", name = "Wooden TV Cabinet"},
    ["p_cs_locker_01_s"] = {type = "storage", itemHash = "locker", name = "Closed Locker"},
    ["p_cs_locker_02"] = {type = "storage", itemHash = "locker2", name = "Open Locker"},
    ["bkr_prop_gunlocker_01a"] = {type = "storage", itemHash = "gunlocker", name = "Gun Locker"},
    ["apa_mp_h_str_shelffloorm_02"] = {type = "storage", itemHash = "shelveunit", name = "Wooden Shelving Unit"},
    ["apa_mp_h_str_shelffreel_01"] = {type = "storage", itemHash = "shelveunit2", name = "Large White Shelves"},
    ["apa_mp_h_str_shelfwallm_01"] = {type = "storage", itemHash = "shelveunit3", name = "Small Wooden Shelves"},
    ["prop_shelves_01"] = {type = "storage", itemHash = "shelveunit4", name = "Large Metal Shelves"},
    ["apa_mp_h_bed_chestdrawer_02"] = {type = "storage", itemHash = "shelveunit5", name = "Purple Dresser"},
    ["v_res_tre_storageunit"] = {type = "storage", itemHash = "shelveunit6", name = "Medium White Dresser"},
    ["v_res_tre_bedsidetableb"] = {type = "storage", itemHash = "shelveunit7", name = "Small White Dresser"},
    ["apa_mp_h_str_sideboardl_06"] = {type = "storage", itemHash = "shelveunit8", name = "Large White Sideboard"},
    ["apa_mp_h_str_sideboardm_03"] = {type = "storage", itemHash = "shelveunit9", name = "Medium White Sideboard"},
    ["apa_mp_h_str_sideboards_01"] = {type = "storage", itemHash = "shelveunit10", name = "Medium Grey Panel Sideboard"},
    ["hei_heist_str_sideboardl_02"] = {type = "storage", itemHash = "shelveunit11", name = "Large Grey Sideboard"},
    ["apa_mp_h_str_sideboardl_11"] = {type = "storage", itemHash = "shelveunit12", name = "Large Grey Wooden Sideboard"},
    ["hei_heist_str_sideboardl_03"] = {type = "storage", itemHash = "shelveunit13", name = "Large Wooden Sideboard"},
    ["apa_mp_h_str_sideboardm_02"] = {type = "storage", itemHash = "shelveunit14", name = "Medium Wooden Sideboard"},
    ["v_ind_rc_locker"] = {type = "storage", itemHash = "greenlocker", name = "Large Green Locker"},
    ["prop_cabinet_02b"] = {type = "storage", itemHash = "shelveunit15", name = "Large Grey Office Cabinet"},
    ["prop_fbibombfile"] = {type = "storage", itemHash = "shelveunit16", name = "Small Grey Office Cabinet"},
    ["v_corp_offshelfdark"] = {type = "storage", itemHash = "shelveunit17", name = "Large Black Office Shelves"},
    ["p_devin_box_01_s"] = {type = "storage", itemHash = "shelveunit18", name = "Open Storage Box"},
    ["v_res_tre_storagebox"] = {type = "storage", itemHash = "shelveunit19", name = "Bamboo Storage Box"},
    ["prop_ld_int_safe_01"] = {type = "storage", itemHash = "shelveunit20", name = "Safe"},

    -- TABLES
    ["apa_mp_h_din_table_05"] = {type = "table", itemHash = "table", name = "Large Dark Wood Dining Table"},
    ["apa_mp_h_din_table_06"] = {type = "table", itemHash = "table2", name = "Large White Dining Table"},
    ["hei_heist_din_table_07"] = {type = "table", itemHash = "table3", name = "Rounded Glass Dining Table"},
    ["hei_heist_din_table_01"] = {type = "table", itemHash = "table4", name = "Large Glass Dining Table 1"},
    ["apa_mp_h_din_table_11"] = {type = "table", itemHash = "table5", name = "Large Glass Dining Table 2"},
    ["hei_heist_din_table_04"] = {type = "table", itemHash = "table6", name = "Medium Glass Dining Table"},
    ["v_res_m_dinetble_replace"] = {type = "table", itemHash = "table7", name = "Round Wooden Dining Table"},
    ["v_res_m_dinetble"] = {type = "table", itemHash = "table8", name = "Round Vintage Wooden Dining Table"},
    ["apa_mp_h_tab_coffee_05"] = {type = "table", itemHash = "table9", name = "Large Grey Coffee Table"},
    ["prop_t_coffe_table"] = {type = "table", itemHash = "table10", name = "Large Black Coffee Table"},
    ["hei_heist_tab_coffee_06"] = {type = "table", itemHash = "table11", name = "Medium Concrete Coffee Table"},
    ["prop_t_coffe_table_02"] = {type = "table", itemHash = "table12", name = "Large Glass Coffee Table"},
    -- ["v_res_fh_coftbldisp"] = {type = "table", itemHash = "table13", name = "Large Metal Glass Coffee Table"}, UNABLE TO REMOVE
    ["apa_mp_h_tab_coffee_08"] = {type = "table", itemHash = "table14", name = "Medium White Coffee Table"},
    --["v_med_p_coffeetable"] = {type = "table", itemHash = "table15", name = "Medium Glass Wood Coffee Table"}, UNABLE TO REMOVE
    ["apa_mp_h_tab_coffee_07"] = {type = "table", itemHash = "table16", name = "Medium Glass Coffee Table 1"},
    ["apa_mp_h_tab_sidelrg_02"] = {type = "table", itemHash = "table17", name = "Medium Glass Coffee Table 2"},
    ["apa_mp_h_tab_sidelrg_01"] = {type = "table", itemHash = "table18", name = "Medium Glass Coffee Table 3"},
    ["v_res_fh_coftableb"] = {type = "table", itemHash = "table19", name = "Medium Light Grey Coffee Table"},
    --["v_res_fh_coftablea"] = {type = "table", itemHash = "table20", name = "Medium Dark Grey Coffee Table"},
    ["apa_mp_h_tab_sidelrg_07"] = {type = "table", itemHash = "table21", name = "Small Glass Coffee Table"},
    ["apa_mp_h_tab_sidesml_01"] = {type = "table", itemHash = "table22", name = "Stacked Glass Side Table"},
    ["apa_mp_h_tab_sidesml_02"] = {type = "table", itemHash = "table23", name = "Small Glass Side Table"},
    ["apa_mp_h_tab_sidelrg_04"] = {type = "table", itemHash = "table24", name = "Round Black Table"},
    ["prop_table_07"] = {type = "table", itemHash = "table25", name = "Round Metal Table"},
    ["v_res_msidetblemod"] = {type = "table", itemHash = "table26", name = "Round Vintage Table"},
    ["hei_heist_str_sideboards_02"] = {type = "table", itemHash = "table27", name = "Long Glass Side Table"},
    ["ex_prop_ex_console_table_01"] = {type = "table", itemHash = "table28", name = "Long Wooden Side Table"},
    ["v_res_m_console"] = {type = "table", itemHash = "table29", name = "Long Dark Wooden Side Table"},
    ["bkr_prop_fakeid_table"] = {type = "table", itemHash = "table30", name = "Small Wooden Table"},
    ["prop_fbi3_coffee_table"] = {type = "table", itemHash = "table31", name = "Small Wooden Side Table"},
    ["prop_ld_farm_table02"] = {type = "table", itemHash = "table32", name = "Cluttered Wooden Table"},
    ["v_corp_conftable2"] = {type = "table", itemHash = "table33", name = "Large Black Conference Table"},
    ["v_res_mddesk"] = {type = "table", itemHash = "table34", name = "White Letter Desk"},
    ["v_res_mddresser"] = {type = "table", itemHash = "table35", name = "White Vanity Desk"},
    ["v_res_mbdresser"] = {type = "table", itemHash = "table36", name = "Vintage Wooden Desk"},
    ["v_corp_officedesk"] = {type = "table", itemHash = "table37", name = "Black Office Computer Desk"},

    -- CHAIRS
    ["hei_heist_din_chair_02"] = {type = "chair", itemHash = "chair", name = "Orange Bucket Chair"},
    ["hei_heist_din_chair_03"] = {type = "chair", itemHash = "chair2", name = "Wood Finish Chair"},
    ["hei_heist_din_chair_05"] = {type = "chair", itemHash = "chair3", name = "Grey Fabric Chair"},
    ["prop_off_chair_05"] = {type = "chair", itemHash = "chair4", name = "Grey Office Seat"},
    ["prop_skid_chair_01"] = {type = "chair", itemHash = "chair5", name = "Green Skid Chair"},
    ["prop_skid_chair_02"] = {type = "chair", itemHash = "chair6", name = "Worn Blue Skid Chair"},
    ["prop_skid_chair_03"] = {type = "chair", itemHash = "chair7", name = "Patterned Skid Chair"},
    ["prop_chair_01a"] = {type = "chair", itemHash = "chair8", name = "Metal Chair"},
    ["v_ret_chair"] = {type = "chair", itemHash = "chair9", name = "Vintage Red Pattern Chair"},
    ["v_res_m_l_chair1"] = {type = "chair", itemHash = "chair10", name = "Vintage Orange Striped Chair"},
    ["v_ret_chair_white"] = {type = "chair", itemHash = "chair11", name = "Vintage White Pattern Chair"},
    ["p_dinechair_01_s"] = {type = "chair", itemHash = "chair12", name = "Wooden Cushioned Dining Chair"},
    ["v_res_tre_chair"] = {type = "chair", itemHash = "chair13", name = "White Wood Dining Chair"},
    ["prop_chair_07"] = {type = "chair", itemHash = "chair14", name = "Used Wooden Chair"},
    ["prop_clown_chair"] = {type = "chair", itemHash = "chair15", name = "Wooden Dining Chair"},
    ["prop_table_01_chr_b"] = {type = "chair", itemHash = "chair16", name = "Outdoors Wooden Chair 1"},
    ["prop_table_02_chr"] = {type = "chair", itemHash = "chair17", name = "Outdoors Wooden Chair 2"},
    ["prop_chair_04a"] = {type = "chair", itemHash = "chair18", name = "Simplistic Wooden Chair 1"},
    ["bkr_prop_weed_chair_01a"] = {type = "chair", itemHash = "chair19", name = "Simplistic Wooden Chair 2"},
    ["prop_chair_04b"] = {type = "chair", itemHash = "chair20", name = "Simplistic White Chair"},
    ["ex_prop_offchair_exec_04"] = {type = "chair", itemHash = "chair21", name = "Black Executive Desk Chair"},
    ["apa_mp_h_stn_chairarm_12"] = {type = "chair", itemHash = "chair22", name = "Black Bucket Chair"},
    ["apa_mp_h_stn_chairarm_13"] = {type = "chair", itemHash = "chair23", name = "Yellow Desk Chair"},
    ["ex_prop_offchair_exec_01"] = {type = "chair", itemHash = "chair24", name = "Black Desk Chair 1"},
    ["v_ret_gc_chair03"] = {type = "chair", itemHash = "chair25", name = "Black Desk Chair 2"},
    ["bkr_prop_biker_boardchair01"] = {type = "chair", itemHash = "chair26", name = "Black Desk Chair 3"},
    ["v_ilev_leath_chr"] = {type = "chair", itemHash = "chair27", name = "Brown Leather Desk Chair"},
    ["prop_off_chair_03"] = {type = "chair", itemHash = "chair28", name = "Used Desk Chair"},
    ["apa_mp_h_din_stool_04"] = {type = "chair", itemHash = "chair29", name = "Rounded White Modern Stool"},
    ["bkr_prop_biker_barstool_02"] = {type = "chair", itemHash = "chair30", name = "Padded White Modern Stool"},
    ["v_res_kitchnstool"] = {type = "chair", itemHash = "chair31", name = "Vintage Wooden Stool"},
    ["v_res_fh_kitnstool"] = {type = "chair", itemHash = "chair32", name = "Square Grey Stool"},
    ["v_res_tre_stool"] = {type = "chair", itemHash = "chair33", name = "Circular Grey Stool"},
    ["v_res_tre_stool_leather"] = {type = "chair", itemHash = "chair34", name = "Circular Brown Leather Stool"},
    -- ["bkr_prop_biker_barstool_03"] = {type = "chair", itemHash = "chair35", name = "Circular Wooden Stool"}, UNABLE TO REMOVE
    ["ba_prop_int_edgy_stool"] = {type = "chair", itemHash = "chair36", name = "Wood and Black Stool"},
    ["ba_prop_int_glam_stool"] = {type = "chair", itemHash = "chair37", name = "Black and Gold Stool"},
    ["v_res_fh_pouf"] = {type = "chair", itemHash = "chair38", name = "Grey Cube Pouf"},
    ["apa_mp_h_yacht_stool_01"] = {type = "chair", itemHash = "chair39", name = "Cream Round Pouf"},
    ["apa_mp_h_stn_chairstool_12"] = {type = "chair", itemHash = "chair40", name = "Small Black Stool"},
    ["apa_mp_h_stn_foot_stool_01"] = {type = "chair", itemHash = "chair41", name = "Grey Table Stool"},
    ["apa_mp_h_stn_foot_stool_02"] = {type = "chair", itemHash = "chair42", name = "White Table Stool"},
    ["apa_mp_h_stn_sofa_daybed_02"] = {type = "chair", itemHash = "chair43", name = "Black Day Chair"},
    ["apa_mp_h_stn_sofa_daybed_01"] = {type = "chair", itemHash = "chair44", name = "Beige Day Chair"},

    -- COUCHES
    ["p_v_med_p_sofa_s"] = {type = "couch", itemHash = "sofa", name = "Padded Brown Leather Sofa"},
    ["prop_t_sofa"] = {type = "couch", itemHash = "sofabed", name = "Sofa Bed"},
    ["v_res_mp_sofa"] = {type = "couch", itemHash = "sofa3", name = "White Corner Sofa"},
    ["apa_mp_h_stn_sofacorn_01"] = {type = "couch", itemHash = "sofa4", name = "Grey Corner Sofa"},
    ["apa_mp_h_stn_sofacorn_09"] = {type = "couch", itemHash = "sofa5", name = "Dark Grey Corner Sofa"},
    ["apa_mp_h_stn_sofacorn_05"] = {type = "couch", itemHash = "sofa6", name = "Blue and Grey Corner Sofa"},
    ["hei_heist_stn_sofacorn_05"] = {type = "couch", itemHash = "sofa7", name = "Blue Grey Corner Sofa"},
    ["apa_mp_h_stn_sofacorn_07"] = {type = "couch", itemHash = "sofa8", name = "Blue and Black Corner Sofa"},
    ["apa_mp_h_stn_sofacorn_06"] = {type = "couch", itemHash = "sofa9", name = "Green Corner Sofa"},
    ["apa_mp_h_stn_sofacorn_10"] = {type = "couch", itemHash = "sofa10", name = "White and Red Corner Sofa"},
    ["apa_mp_h_yacht_sofa_01"] = {type = "couch", itemHash = "sofa11", name = "Large Cream and Wood Sofa"},
    ["apa_mp_h_yacht_sofa_02"] = {type = "couch", itemHash = "sofa12", name = "Brown Leather Sofa"},
    ["bkr_prop_clubhouse_sofa_01a"] = {type = "couch", itemHash = "sofa13", name = "Black Leather Sofa"},
    ["ex_mp_h_off_sofa_02"] = {type = "couch", itemHash = "sofa14", name = "Black Modern Sofa"},
    ["ex_mp_h_off_sofa_003"] = {type = "couch", itemHash = "sofa15", name = "Grey Modern Sofa"},
    ["ex_mp_h_off_sofa_01"] = {type = "couch", itemHash = "sofa16", name = "White Modern Sofa"},
    ["apa_mp_h_stn_sofa2seat_02"] = {type = "couch", itemHash = "sofa17", name = "White Love Seat Modern Sofa"},
    ["v_res_m_h_sofa"] = {type = "couch", itemHash = "sofa18", name = "Vintage Cream Sofa"},
    ["p_res_sofa_l_s"] = {type = "couch", itemHash = "sofa19", name = "Vintage Pattern Sofa"},
    ["hei_heist_stn_sofa3seat_01"] = {type = "couch", itemHash = "sofa20", name = "Grey Day Sofa"},
    ["hei_heist_stn_sofa3seat_02"] = {type = "couch", itemHash = "sofa21", name = "3 Seat Brown Sofa"},
    ["hei_heist_stn_sofa3seat_06"] = {type = "couch", itemHash = "sofa22", name = "3 Seat Grey Sofa"},
    ["prop_couch_01"] = {type = "couch", itemHash = "sofa23", name = "Cream Brown Yellow Pattern Sofa"},
    ["prop_couch_03"] = {type = "couch", itemHash = "sofa24", name = "Brown Yellow Pattern Sofa"},
    ["prop_couch_lg_07"] = {type = "couch", itemHash = "sofa25", name = "Wide Modern White Sofa"},
    ["miss_rub_couch_01"] = {type = "couch", itemHash = "sofa26", name = "Grandma's Used Sofa"},
    ["prop_ld_farm_couch02"] = {type = "couch", itemHash = "sofa27", name = "Used Striped Green Sofa"},
    ["prop_fib_3b_bench"] = {type = "couch", itemHash = "sofa28", name = "Brown Leather Bench"},
    ["prop_wait_bench_01"] = {type = "couch", itemHash = "sofa29", name = "Black Leather Bench"},

    -- BEDS
    ["v_res_msonbed"] = {type = "bed", itemHash = "bed", name = "Black and Red Double Bed"},
    ["p_lestersbed_s"] = {type = "bed", itemHash = "bed2", name = "Brown Wooden Double Bed"},
    ["apa_mp_h_bed_double_08"] = {type = "bed", itemHash = "bed3", name = "Black Double Bed"},
    ["apa_mp_h_bed_double_09"] = {type = "bed", itemHash = "bed4", name = "Grey Double Bed"},
    ["apa_mp_h_bed_wide_05"] = {type = "bed", itemHash = "bed5", name = "Red Triple Bed"},
    ["apa_mp_h_bed_with_table_02"] = {type = "bed", itemHash = "bed6", name = "Black Sideboard Double Bed"},
    ["apa_mp_h_yacht_bed_01"] = {type = "bed", itemHash = "bed7", name = "Grey Triple Bed"},
    ["apa_mp_h_yacht_bed_02"] = {type = "bed", itemHash = "bed8", name = "Black Triple Bed"},
    ["p_mbbed_s"] = {type = "bed", itemHash = "bed9", name = "Vintage Wooden Double Bed"},
    ["v_res_mdbed"] = {type = "bed", itemHash = "bed10", name = "Vintage White Double Bed"},
    ["v_res_tre_bed1"] = {type = "bed", itemHash = "bed11", name = "White and Green Double Bed"},
    ["v_res_tre_bed2"] = {type = "bed", itemHash = "bed12", name = "Blue Wooden Double Bed"},
    ["gr_prop_bunker_bed_01"] = {type = "bed", itemHash = "bed13", name = "Grey Metal Bed"},
    ["ex_prop_exec_bed_01"] = {type = "bed", itemHash = "bed14", name = "Brown Leather Bed"},
    ["bkr_prop_biker_campbed_01"] = {type = "bed", itemHash = "bed15", name = "Green Military Bed"},
    ["prop_skid_sleepbag_1"] = {type = "bed", itemHash = "bed16", name = "Red Sleeping Bag"},

    -- PLANTS
    ["prop_pot_plant_04b"] = {type = "plants", itemHash = "pottedplant", name = "Potted Plant"},
    ["v_res_fa_plant01"] = {type = "plants", itemHash = "pottedplant2", name = "Small Potted Plant"},
    ["prop_peyote_highland_02"] = {type = "plants", itemHash = "pottedplant3", name = "Small Potted Succulents"},
    ["v_ret_ps_flowers_01"] = {type = "plants", itemHash = "pottedplant4", name = "White Bird Of Paradise Vase"},
    ["v_res_rosevase"] = {type = "plants", itemHash = "pottedplant5", name = "White Rose Vase"},
    ["v_res_mflowers"] = {type = "plants", itemHash = "pottedplant6", name = "Pink Lily Vase"},
    ["v_res_exoticvase"] = {type = "plants", itemHash = "pottedplant7", name = "Green Bird Of Paradise Vase"},
    ["v_res_rubberplant"] = {type = "plants", itemHash = "pottedplant8", name = "Rubber Plant"},
    ["v_res_ivy"] = {type = "plants", itemHash = "pottedplant9", name = "Ivy Plant"},
    ["prop_plant_int_04a"] = {type = "plants", itemHash = "pottedplant10", name = "Small House Plant"},
    ["prop_plant_int_04b"] = {type = "plants", itemHash = "pottedplant11", name = "Bonsai Tree"},
    ["prop_pot_plant_01a"] = {type = "plants", itemHash = "pottedplant12", name = "Medium House Plant"},
    ["apa_mp_h_acc_vase_flowers_01"] = {type = "plants", itemHash = "pottedplant13", name = "Large Calla Lily Vase"},
    ["apa_mp_h_acc_vase_flowers_02"] = {type = "plants", itemHash = "pottedplant14", name = "Hydrangea Vase"},
    ["apa_mp_h_acc_vase_flowers_03"] = {type = "plants", itemHash = "pottedplant15", name = "Large Calla Lily Pot"},
    ["apa_mp_h_acc_vase_flowers_04"] = {type = "plants", itemHash = "pottedplant16", name = "Chinese Lantern Flower Circular Vase"},
    ["hei_heist_acc_flowers_02"] = {type = "plants", itemHash = "pottedplant17", name = "Chinese Lantern Flower Vase"},
    ["v_res_mvasechinese"] = {type = "plants", itemHash = "pottedplant18", name = "Chinese Lantern Flower Pot"},
    ["hei_heist_acc_flowers_01"] = {type = "plants", itemHash = "pottedplant19", name = "Small Calla Lily Vase"},
    ["p_int_jewel_plant_02"] = {type = "plants", itemHash = "pottedplant20", name = "Large Decorative House Plant"},
    ["prop_fbibombplant"] = {type = "plants", itemHash = "pottedplant21", name = "Large Tree House Plant"},
    ["prop_pot_plant_05a"] = {type = "plants", itemHash = "pottedplant22", name = "Large Leaf House Plant"},
    ["apa_mp_h_acc_plant_palm_01"] = {type = "plants", itemHash = "pottedplant23", name = "Large Palm House Plant"},
    ["apa_mp_h_acc_plant_tall_01"] = {type = "plants", itemHash = "pottedplant24", name = "Grey Box Snake Plant"},
    ["v_res_mplanttongue"] = {type = "plants", itemHash = "pottedplant25", name = "Round Pot Snake Plant"},
    -- ["v_med_p_planter"] = {type = "plants", itemHash = "pottedplant26", name = "Tube Pot Snake Plant"}, UNABLE TO REMOVE
    ["prop_xmas_tree_int"] = {type = "plants", itemHash = "christmastree", name = "Christmas Tree"},

    -- ELECTRONICS
    ["prop_tv_flat_02"] = {type = "electronic", itemHash = "flattv", name = "Small Flatscreen TV"},
    ["prop_cs_tv_stand"] = {type = "electronic", itemHash = "tvstand", name = "Vintage TV Stand"},
    ["apa_mp_h_str_avunitl_01_b"] = {type = "electronic", itemHash = "tvunit", name = "Large Wooden TV Unit"},
    ["apa_mp_h_str_avunitl_04"] = {type = "electronic", itemHash = "tvunit2", name = "Large White TV Unit"},
    ["apa_mp_h_str_avunits_04"] = {type = "electronic", itemHash = "tvunit3", name = "Metal TV Unit"},
    ["hei_heist_str_avunitl_03"] = {type = "electronic", itemHash = "tvunit4", name = "White TV Unit"},
    ["des_tvsmash_start"] = {type = "electronic", itemHash = "tvunit5", name = "Large TV"},
    ["prop_tv_03"] = {type = "electronic", itemHash = "tvunit6", name = "CRT TV"},
    ["prop_tv_05"] = {type = "electronic", itemHash = "tvunit7", name = "Vintage TV"},
    ["bkr_prop_clubhouse_jukebox_01b"] = {type = "electronic", itemHash = "jukebox", name = "Large Jukebox"},
    ["bkr_prop_clubhouse_jukebox_01a"] = {type = "electronic", itemHash = "jukebox2", name = "Medium Jukebox"},
    ["bkr_prop_clubhouse_jukebox_02a"] = {type = "electronic", itemHash = "jukebox3", name = "Vintage Jukebox"},
    ["prop_tv_flat_01"] = {type = "electronic", itemHash = "tvunit8", name = "Large Wall TV"},
    ["prop_tv_flat_michael"] = {type = "electronic", itemHash = "tvunit9", name = "Medium TV"},
    ["prop_dj_deck_02"] = {type = "electronic", itemHash = "djdeck", name = "DJ Deck"},
    ["p_amb_lap_top_02"] = {type = "electronic", itemHash = "laptop", name = "Laptop"},
    ["ex_prop_monitor_01_ex"] = {type = "electronic", itemHash = "ifruitcomputer", name = "iFruit Computer"},
    ["prop_monitor_w_large"] = {type = "electronic", itemHash = "pcmonitor", name = "PC Monitor"},
    ["prop_dyn_pc_02"] = {type = "electronic", itemHash = "pctower", name = "PC Tower"},
    ["hei_prop_hei_cs_keyboard"] = {type = "electronic", itemHash = "keyboard", name = "Keyboard"},
    ["bkr_prop_money_counter"] = {type = "electronic", itemHash = "moneycounter", name = "Money Counter"},
    ["prop_office_phone_tnt"] = {type = "electronic", itemHash = "officephone", name = "Office Phone"},
    ["apa_mp_h_acc_phone_01"] = {type = "electronic", itemHash = "greenphone", name = "Green Phone"},
    ["prop_printer_02"] = {type = "electronic", itemHash = "printer", name = "Printer"},
    ["prop_shredder_01"] = {type = "electronic", itemHash = "shreddermachine", name = "Paper Shredder Machine"},
    ["prop_copier_01"] = {type = "electronic", itemHash = "copymachine", name = "Photocopier Machine"},
    ["prop_pap_camera_01"] = {type = "electronic", itemHash = "camera", name = "DLR Pap Camera"},
    ["hei_prop_bank_cctv_01"] = {type = "electronic", itemHash = "securitycamera", name = "Security Camera"},
    ["prop_mp3_dock"] = {type = "electronic", itemHash = "speakerdock", name = "Phone Speaker Dock"},
    ["prop_speaker_06"] = {type = "electronic", itemHash = "smallspeaker", name = "Small Black Speaker"},
    ["prop_speaker_03"] = {type = "electronic", itemHash = "largespeaker", name = "Large Wooden Speaker"},
    ["prop_speaker_07"] = {type = "electronic", itemHash = "largespeaker2", name = "Large Black Speaker"},
    ["prop_arcade_01"] = {type = "electronic", itemHash = "arcademachine", name = "QUB3D Arcade Machine"},
    ["gr_prop_bunker_deskfan_01a"] = {type = "electronic", itemHash = "deskfan", name = "Desk Fan"},
    ["bkr_prop_weed_fan_floor_01a"] = {type = "electronic", itemHash = "floorfan", name = "Floor Fan"},
    ["v_res_fa_fan"] = {type = "electronic", itemHash = "whiteboxfan", name = "White Box Fan"},

    -- LIGHTS
    ["apa_mp_h_lit_floorlamp_03"] = {type = "electronic", itemHash = "lamp", name = "Angular Black Floor Lamp"},
    ["apa_mp_h_lit_floorlamp_06"] = {type = "electronic", itemHash = "lamp2", name = "Curved Black Floor Lamp"},
    ["apa_mp_h_floorlamp_b"] = {type = "electronic", itemHash = "lamp3", name = "Angular White Floor Lamp"},
    ["apa_mp_h_lit_floorlamp_01"] = {type = "electronic", itemHash = "lamp4", name = "Angular Metal Floor Lamp"},
    ["apa_mp_h_lit_floorlamp_05"] = {type = "electronic", itemHash = "lamp5", name = "Curved Grey Floor Lamp"},
    ["apa_mp_h_floorlamp_c"] = {type = "electronic", itemHash = "lamp6", name = "Grey Floor Lamp"},
    ["apa_mp_h_lit_floorlampnight_07"] = {type = "electronic", itemHash = "lamp7", name = "Blue Floor Lamp"},
    ["apa_mp_h_lit_floorlampnight_14"] = {type = "electronic", itemHash = "lamp8", name = "Cream Floor Lamp"},
    ["apa_mp_h_lit_floorlamp_17"] = {type = "electronic", itemHash = "lamp9", name = "White Floor Lamp"},
    ["apa_mp_h_floorlamp_a"] = {type = "electronic", itemHash = "lamp10", name = "Long Cream Floor Lamp"},
    ["apa_mp_h_lit_floorlamp_13"] = {type = "electronic", itemHash = "lamp11", name = "Long Pink Floor Lamp"},
    ["apa_mp_h_lit_floorlamp_10"] = {type = "electronic", itemHash = "lamp12", name = "Spiky White Floor Lamp"},
    ["apa_mp_h_yacht_floor_lamp_01"] = {type = "electronic", itemHash = "lamp13", name = "Brown and White Floor Lamp"},
    ["hei_heist_lit_floorlamp_04"] = {type = "electronic", itemHash = "lamp14", name = "Tilted Cream Floor Lamp"},
    ["apa_mp_h_lit_lamptable_04"] = {type = "electronic", itemHash = "lamp15", name = "Cream Squared Table Lamp"},
    ["apa_mp_h_lit_lamptable_005"] = {type = "electronic", itemHash = "lamp16", name = "White Squared Table Lamp"},
    ["apa_mp_h_yacht_table_lamp_02"] = {type = "electronic", itemHash = "lamp17", name = "Brown and White Table Lamp"},
    ["apa_mp_h_lit_lamptable_21"] = {type = "electronic", itemHash = "lamp18", name = "Small Black and White Table Lamp"},
    ["hei_heist_lit_lamptable_06"] = {type = "electronic", itemHash = "lamp19", name = "Black and White Spherical Table Lamp"},
    ["apa_mp_h_lit_lamptable_17"] = {type = "electronic", itemHash = "lamp20", name = "Paper Lantern Table Lamp"},
    ["hei_heist_lit_lamptable_03"] = {type = "electronic", itemHash = "lamp21", name = "Tilted Cream Table Lamp"},
    ["apa_mp_h_lit_lamptablenight_16"] = {type = "electronic", itemHash = "lamp22", name = "White Table Lamp"},
    ["apa_mp_h_lit_lamptablenight_24"] = {type = "electronic", itemHash = "lamp23", name = "Black Table Lamp"},
    ["apa_mp_h_lit_lamptable_09"] = {type = "electronic", itemHash = "lamp24", name = "Brown Table Lamp"},
    ["v_res_j_tablelamp2"] = {type = "electronic", itemHash = "lamp25", name = "Small Brown Table Lamp"},
    ["v_res_j_tablelamp1"] = {type = "electronic", itemHash = "lamp26", name = "Wide Brown Table Lamp"},
    ["v_res_m_lamptbl"] = {type = "electronic", itemHash = "lamp27", name = "Vintage Cream Table Lamp"},
    ["v_res_m_candle"] = {type = "electronic", itemHash = "candle", name = "Black and Red Candle"},
    ["v_res_m_candlelrg"] = {type = "electronic", itemHash = "candle2", name = "Vintage White Candle"},
    ["hei_prop_hei_bnk_lamp_01"] = {type = "electronic", itemHash = "lamp28", name = "Green Desk Lamp"},
    ["apa_mp_h_lit_lamptable_14"] = {type = "electronic", itemHash = "lamp29", name = "White Desk Lamp"},
    ["apa_mp_h_lit_lamptable_02"] = {type = "electronic", itemHash = "lamp30", name = "Black Desk Lamp"},
    ["hei_heist_lit_lightpendant_02"] = {type = "electronic", itemHash = "lamp31", name = "Orange Ceiling Light"},
    ["apa_mp_h_lit_lightpendant_05"] = {type = "electronic", itemHash = "lamp32", name = "Black Ceiling Light"},
    ["apa_mp_h_lit_lightpendant_05b"] = {type = "electronic", itemHash = "lamp33", name = "Wooden Ceiling Light"},
    ["apa_mp_h_lit_lightpendant_01"] = {type = "electronic", itemHash = "lamp34", name = "Cream Squared Ceiling Light"},
    ["bkr_prop_biker_ceiling_fan_base"] = {type = "electronic", itemHash = "lamp35", name = "Ceiling Fan Light"},
    ["prop_oldlight_01c"] = {type = "electronic", itemHash = "lamp36", name = "Metal Ceiling Light"},

    -- MISCELLEANOUS
    ["prop_gnome1"] = {type = "misc", itemHash = "gnome1", name = "Fishing Gnome"},
    ["prop_gnome2"] = {type = "misc", itemHash = "gnome2", name = "Gnome with a Bag"},
    ["prop_gnome3"] = {type = "misc", itemHash = "gnome3", name = "Mooning Gnome"},
    ["gr_prop_gr_bench_04a"] = {type = "misc", itemHash = "workbench", name = "Crafting Workbench"},
    ["apa_mp_h_acc_rugwooll_03"] = {type = "misc", itemHash = "rug", name = "Large Beige Wool Rug"},
    ["apa_mp_h_acc_rugwooll_04"] = {type = "misc", itemHash = "rug2", name = "Large Wool Textured Rug"},
    ["hei_heist_acc_rughidel_01"] = {type = "misc", itemHash = "rug3", name = "Large Cow Skin Rug"},
    ["hei_heist_acc_rugwooll_01"] = {type = "misc", itemHash = "rug4", name = "Large Orange, Black And White Rug"},
    ["apa_mp_h_acc_rugwoolm_01"] = {type = "misc", itemHash = "rug5", name = "Medium Orange, Black And White Rug"},
    ["apa_mp_h_acc_rugwoolm_02"] = {type = "misc", itemHash = "rug6", name = "Medium Blue, Black And White Rug"},
    ["apa_mp_h_acc_rugwoolm_03"] = {type = "misc", itemHash = "rug7", name = "Medium White To Black Gradient Rug"},
    ["apa_mp_h_acc_rugwoolm_04"] = {type = "misc", itemHash = "rug8", name = "Medium Grey Boxy Rug"},
    ["apa_mp_h_acc_rugwools_01"] = {type = "misc", itemHash = "rug9", name = "Small Grey Circle Pattern Rug"},
    ["apa_mp_h_acc_rugwools_03"] = {type = "misc", itemHash = "rug10", name = "Small Cream And Blue Rug"},
    ["p_yoga_mat_03_s"] = {type = "misc", itemHash = "rug11", name = "Red Yoga Mat"},
    ["p_yoga_mat_02_s"] = {type = "misc", itemHash = "rug12", name = "Grey Yoga Mat"},
    ["p_shower_towel_s"] = {type = "misc", itemHash = "rug13", name = "White Towel"},
    ["vw_prop_vw_colle_alien"] = {type = "misc", itemHash = "bs_toy_alien", name = "Alien Toy"},
    ["vw_prop_vw_colle_prbubble"] = {type = "misc", itemHash = "bs_toy_bubblegum", name = "Princess Robot Bubblegum Toy"},
    ["vw_prop_vw_colle_pogo"] = {type = "misc", itemHash = "bs_toy_monkey", name = "Space Monkey Toy"},
    ["vw_prop_vw_colle_sasquatch"] = {type = "misc", itemHash = "bs_toy_sasquatch", name = "Bigfoot Toy"},
    ["vw_prop_vw_colle_rsrcomm"] = {type = "misc", itemHash = "bs_toy_spaceman", name = "Space Ranger Toy"},
    ["vw_prop_vw_colle_rsrgeneric"] = {type = "misc", itemHash = "bs_toy_spaceman2", name = "Space Ranger 2 Toy"},
    ["vw_prop_vw_colle_imporage"] = {type = "misc", itemHash = "bs_toy_superhero", name = "Impotent Rage Toy"},
    ["vw_prop_vw_colle_beast"] = {type = "misc", itemHash = "bs_toy_wolf", name = "The Beast Toy"},
}