-- CUSTOMER DESTINATIONS
taxiCalls = {
    [1] = {x = 285.8, y = -607.1, z = 43.1, name = "Pillbox Hospital", msg = "Hey what's up, take me to the upper portion of Pillbox Hospital on Elgin Ave in Textile City, please."},
    [2] = {x = 253.3, y = -375.8, z = 44.4, name = "Courthouse", msg = "How's it going? I need you to take me to the Courthouse on Occupation Ave and Elgin Ave in Alta, please."},
    [3] = {x = 120.8, y = -300.4, z = 45.5, name = "Occupation Ave / Capital Blvd", msg = "The apartments on Occupation Ave and Captial Blvd in Alta, please."},
    [4] = {x = -506.4, y = -257.21, z = 35.64, name = "City Hall", msg = "Hello! Can you please take me to City Hall on Carcer Way in Burton, please."},
    [5] = {x = -466.36, y = -351.99, z = 34.5, name = "Mount Zonah", msg = "Hey! My friend is in the hospital. Can you take me to Mount Zonah Hospital on Dorset Drive and Carcer Way in Rockford Hills? Please and thank you."},
    [6] = {x = -258.23, y = -299.5, z = 29.88, name = "San Vitus Blvd / Abe Milton Pkwy", msg = "Heyo, I need you to take me to White Widow on San Vitus Blvd and Abe Milton Pkwy in Burton."},
    [7] = {x = -423.65, y = -23.56, z = 45.7, name = "Cockatoos Nightclub", msg = "Yo yo! Can you take me to that Cockatoos nightclub on Hawick Ave and Eastbourne Way? Thank you."},
    [8] = {x = -424.31, y = 15.26, z = 45.77, name = "SAGMA Gallery", msg = "Howdy. I need you to take me to SAGMA Gallery on Hawick Ave and Eastbourne Way in West Vinewood. Pronto."},
    [9] = {x = -527.24, y = -28.9, z = 43.99, name = "Little Teapot", msg = "I gotta meet a date at the Little Teapot on Hawick Ave and Milton Rd! Step on it!"},
    [10] = {x = -646.09, y = 36.21, z = 39.14, name = "Tinsel Towers", msg = "I forgot something back at the Tinsel Towers on Strangeways Dr and Boulevard Del Perro. Thanks in advance."},
    [11] = {x = -689.41, y = 40.98, z = 42.68, name = "Epsilon Building", msg = "Kifflom! I need you to take me to the Epsilon building on Strangeways Dr. May Kraff be with you."},
    [12] = {x = -649.5, y = -126.66, z = 37.27, name = "Rockford FD", msg = "I got an interview with the local fire department at the station on Rockford Drive! Please and thanks!"},
    [13] = {x = -714.94, y = -171.32, z = 36.28, name = "Portola Ponsonbys", msg = "I heard the Ponsonbys on Portola Drive in Rockford Hills has some nice deals! Take me there please!"},
    [14] = {x = -648.45, y = -691.0, z = 30.08, name = "Taco Bomb", msg = "I hear that Taco Bomb on Palomino Ave and San Andreas Ave in Little Seouls has some pretty good tacos. Thanks for the ride!"},
    [15] = {x = -665.78, y = -951.56, z = 20.75, name = "Little Seoul Ammu-Nation", msg = "My daughter got a new boyfriend that I think is pretty fucking shady. Take me to the gun store on Lindsay Circus and Palomino Ave. I gotta be prepared."},
    [16] = {x = -708.49, y = -920.5, z = 18.49, name = "Lindsay Cirucs LTD", msg = "The gas station on Lindsay Circus and Palomino Ave in Little Seoul, please!"},
    [17] = {x = -147.7, y = -306.59, z = 38.35, name = "Las Lagunas Blvd Ponsonbys", msg = "The clothing store on Las Lagunas Blvd, I heard they got a nice jacket. Thank you in advance."},
    [18] = {x = -299.0, y = -618.91, z = 33.02, name = "Daily Globe International", msg = "I'm late for my interview at Daily Globe International on San Andreas Ave in Downtown! Hurry up!"},
    [19] = {x = -345.95, y = -832.26, z = 31.56, name = "Vespucci Garage", msg = "Hello! How goes it? I left my car at Vespucci Garage. I hope I don't encounter any drama there."},
    [20] = {x = -224.5, y = -894.4, z = 29.74, name = "Vespucci Blvd PostOp", msg = "I'm late for my interview with PostOp in Vespucci Blvd and Alta St! Step on it please!"},
    [21] = {x = -237.17, y = -989.1, z = 29.13, name = "3 Alta Street", msg = "Heyo, I'm meeting a friend at the '3 Alta Street' apartments. Please get me there quick!"},
    [22] = {x = -213.84, y = -1004.83, z = 29.14, name = "Alta Train Station", msg = "Howdy! I'm taking a train at the Alta Train Station, please and thanks."},
    [23] = {x = -279.35, y = -1063.43, z = 25.91, name = "Alta Banner Hotel", msg = "The Banner Hotel on Alta St please."},
    [24] = {x = -158.82, y = -1151.4, z = 23.1, name = "Adam's Apple Blvd Vapid Dealership", msg = "Ey! I'm really happy! Can you take me to the Vapid dealership on Adam's Apple Blvd please. I'm getting a new car!"},
    [25] = {x = 18.11, y = -1355.28, z = 29.23, name = "Innocence Blvd 24/7", msg = "The convenience store on Innocence Blvd please. I need to get some cigarettes."},
    [26] = {x = 130.32, y = -1307.16, z = 29.17, name = "Vanilla Unicorn", msg = "Sup dude. Can you take me to the Vanilla Unicorn please? I need to get my mind off things."},
    [27] = {x = -188.32, y = -1605.51, z = 33.97, name = "Chamberlain Hills", msg = "What's going on dude. I need to go to the apartments in Chamberlain Hills. Make it quick."},
    [28] = {x = -1034.89, y = -2507.68, z = 20.05, name = "LSIA Arrivals 1", msg = "I'm going to see a longtime friend, take me to the LSIA arrivals."},
    [29] = {x = -1030.48, y = -2733.18, z = 20.03, name = "LSIA Arrivals 2", msg = "How's it goin? Take me to LSIA arrivals please."},
    [30] = {x = -1027.26, y = -2503.76, z = 13.7, name = "LSIA Departures 1", msg = "I'm heading out of state. Take me to LSIA departures please. Hurry up too."},
    [31] = {x = -1024.59, y = -2728.45, z = 13.28, name = "LSIA Departures 2", msg = "I'm leaving San Andreas. I'm late for my flight and I'm panicking. Please take me to LSIA departures and make it quick."},
    [32] = {x = 310.01, y = -265.29, z = 53.79, name = "Alta Bank", msg = "I need you to take me to the bank on Alta. Please and thanks."},
    [33] = {x = 926.56, y = 51.86, z = 80.76, name = "Casino", msg = "WOO! Time to party tonight. I am going to get so wasted. Take me to the Vinewood Casino please and thanks."},
    [34] = {x = 1082.04, y = 251.26, z = 80.46, name = "Racetrack", msg = "I'm going to watch the race tonight! Take me to the Vinewood Racetrack please!"},
    [35] = {x = 775.03, y = 594.0, z = 125.92, name = "Vinewood Bowl", msg = "Take me to the Vinewood Bowl please."},
    [36] = {x = -430.96, y = 1183.78, z = 325.8, name = "Galileo Observatory", msg = "Howdy! I haven't been to the Galileo Observatory in such a long time, could you please take me there?"},
    [37] = {x = -1094.49, y = 2696.04, z = 19.9, name = "Zancudo Plaza", msg = "Take me to the plaza with the gun and clothing store on Route 68 in Great Chaparral"},
    [38] = {x = 211.39, y = 2469.44, z = 55.59, name = "Harmony Garage", msg = "Yo, I need you to take me to Harmony Garage please!"},
    [39] = {x = 617.36, y = 2733.21, z = 41.98, name = "Route 68 Clothing Store", msg = "Hey there. I heard that the Harmony clothing store has some sweet deals, could you please take me there?"},
    [40] = {x = 1174.84, y = 2695.19, z = 37.92, name = "Harmony Bank", msg = "Hello. I need you to take me to Harmony Bank please."},
    [41] = {x = 1859.28, y = 2584.16, z = 45.28, name = "Bollingbroke", msg = "I need to visit a friend at the prison. Please and thanks."},
    [42] = {x = 1842.08, y = 3667.08, z = 33.68, name = "Sandy Medical", msg = "Thank god you stopped. Nobody would! I need you to take me to Sandy Medical to visit a friend."},
    [43] = {x = 1680.01, y = 4819.46, z = 41.95, name = "Grapeseed Clothing Store", msg = "What's going on bud. I need you to take me to the Grapeseed Clothing Store."},
    [44] = {x = -115.78, y = 6457.97, z = 31.47, name = "Paleto Bank", msg = "I need you to take me to Paleto Bank please."}
}
