numberOfBuriedItems = 2750
prospectingRewards = {
    {data = {desc = "a dog collar", itemName = "dogcollar"}},
    {data = {desc = "a broken belt buckle", itemName = "brokenbeltbuckle"}},
    {data = {desc = "a pair of earrings", itemName = "earrings", valuable = true}},
    {data = {desc = "a necklace", itemName = "necklace", valuable = true}},
    {data = {desc = "a bracelet", itemName = "bracelet", valuable = true}},
    {data = {desc = "a gold watch", itemName = "goldwatch", valuable = true}},
    {data = {desc = "a gold ring", itemName = "goldring", valuable = true}},
    {data = {desc = "a gold tooth", itemName = "goldtooth", valuable = true}},
    {data = {desc = "a lucky coin", itemName = "luckycoin", valuable = true}},
    {data = {desc = "a empty soda can", itemName = "emptysodacan"}},
    {data = {desc = "a switchblade", itemName = "WEAPON_SWITCHBLADE"}},
    {data = {desc = "lockpicks", itemName = "lockpick", quantity = 5}},
    {data = {desc = "scrap metal", itemName = "scrapmetal"}},
    {data = {desc = "musket ball", itemName = "musketball", quantity = 6}},
    {data = {desc = "cannon ball", itemName = "cannonball"}},
    {data = {desc = "old coat button", itemName = "oldcoatbutton"}},
    {data = {desc = "old fork", itemName = "oldfork"}},
    {data = {desc = "old spoon", itemName = "oldspoon"}},
    {data = {desc = "old knife", itemName = "oldknife"}},
    {data = {desc = "rusty slim jim", itemName = "rustyslimjim"}},
    {data = {desc = "rusty multitool", itemName = "rustymultitool"}},
    {data = {desc = "foreign coins", itemName = "foreigncoins", quantity = 2}},
    {data = {desc = "bad spark plug", itemName = "badsparkplug"}},
    {data = {desc = "broken cell phone", itemName = "brokencellphone"}},
    {data = {desc = "rusty nail", itemName = "rustynail", quantity = 4}},
    {data = {desc = "bottle cap", itemName = "bottlecap", quantity = 8}},
    {data = {desc = "dog tag", itemName = "dogtag"}},
    {data = {desc = "rusty axe head", itemName = "rustyAxeHead"}},
    {data = {desc = "rusty axe head", itemName = "corrodedbulletcasing"}},
    {data = {desc = "rusty flip lighter", itemName = "rustyfliplighter"}},
    {data = {desc = "rusty pocket watch", itemName = "rustypocketwatch"}}
}
